version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: sj26/mailcatcher
#    image: schickling/mailcatcher ### old image. The new image is coming from the composer symfony/mailer recipe
    ports: ["1025", "1080"]
###< symfony/mailer ###
