controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#login_check:
#    path: /login_check

#home:
#    path: /
#    controller: App\Controller\HomeController::home